$html .= '<tr>';
    $html .= '<td>' . $category->id . '</td>';
    $html .= '<td style="padding-left: ' . ($level * 20) . 'px">';
    $html .= str_repeat('--', $level) . ' ' . $category->name;
    $html .= '</td>';
    $html .= '<td>' . $category->slug . '</td>';
    $html .= '<td>' . $category->created_at . '</td>';
    $html .= '<td>';
    $html .= '<div class="d-flex align-items-center list-action">';
    $html .= '<a class="badge bg-success mr-2" data-toggle="tooltip" data-placement="top" title="Edit" href="' . route('admin.categories.edit', $category->id) . '">';
    $html .= '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>';
    $html .= '</a>';
    $html .= '<form action="' . route('admin.categories.destroy', $category->id) . '" method="post">';
    $html .= csrf_field();
    $html .= method_field('DELETE');
    $html .= '<a href="' . route('admin.categories.destroy', $category->id) . '" class="badge bg-warning mr-2" data-toggle="tooltip" data-placement="top" title="" onclick="return confirm(\'Bạn có chắc muốn xóa bài viết này không?\')">';
    $html .= '<i class="fa fa-trash" aria-hidden="true"></i>';
    $html .= '</a>';
    $html .= '</form>';
    $html .= '</div>';
    $html .= '</td>';
    $html .= '</tr>';
